export const actionType = {
  FETCHING_COLLECTIONS_START: 'FETCHING_COLLECTIONS_START',
  FETCHING_COLLECTIONS_SUCCESS: 'FETCHING_COLLECTIONS_SUCCESS',
  FETCHING_COLLECTIONS_FAILURE: 'FETCHING_COLLECTIONS_FAILURE',
  UPDATE_COLLECTIONS: 'UPDATE_COLLECTIONS'
};